package com.altaie.socialdownloader.ui.theme
import androidx.compose.ui.graphics.Color


val light_primary = Color(0xFF8e437e)
val light_onPrimary = Color(0xFFffffff)
val light_primaryContainer = Color(0xFFffd7f2)
val light_onPrimaryContainer = Color(0xFF3a0033)
val light_secondary = Color(0xFF6f5867)
val light_onSecondary = Color(0xFFffffff)
val light_secondaryContainer = Color(0xFFf9daec)
val light_onSecondaryContainer = Color(0xFF281623)
val light_tertiary = Color(0xFF006a69)
val light_onTertiary = Color(0xFFffffff)
val light_tertiaryContainer = Color(0xFF6ff7f5)
val light_onTertiaryContainer = Color(0xFF002020)
val light_error = Color(0xFFba1b1b)
val light_errorContainer = Color(0xFFffdad4)
val light_onError = Color(0xFFffffff)
val light_onErrorContainer = Color(0xFF410001)
val light_background = Color(0xFFfcfcfc)
val light_onBackground = Color(0xFF1f1a1d)
val light_surface = Color(0xFFfcfcfc)
val light_onSurface = Color(0xFF1f1a1d)
val light_surfaceVariant = Color(0xFFefdee6)
val light_onSurfaceVariant = Color(0xFF4f434a)
val light_outline = Color(0xFF80737a)
val light_inverseOnSurface = Color(0xFFf9eef2)
val light_inverseSurface = Color(0xFF342f32)
val light_inversePrimary = Color(0xFFfface9)
val light_shadow = Color(0xFF000000)

val dark_primary = Color(0xFFfface9)
val dark_onPrimary = Color(0xFF57124c)
val dark_primaryContainer = Color(0xFF732b65)
val dark_onPrimaryContainer = Color(0xFFffd7f2)
val dark_secondary = Color(0xFFdcbed0)
val dark_onSecondary = Color(0xFF3e2b38)
val dark_secondaryContainer = Color(0xFF56404f)
val dark_onSecondaryContainer = Color(0xFFf9daec)
val dark_tertiary = Color(0xFF4ddad9)
val dark_onTertiary = Color(0xFF003737)
val dark_tertiaryContainer = Color(0xFF005050)
val dark_onTertiaryContainer = Color(0xFF6ff7f5)
val dark_error = Color(0xFFffb4a9)
val dark_errorContainer = Color(0xFF930006)
val dark_onError = Color(0xFF680003)
val dark_onErrorContainer = Color(0xFFffdad4)
val dark_background = Color(0xFF1f1a1d)
val dark_onBackground = Color(0xFFe9e0e3)
val dark_surface = Color(0xFF1f1a1d)
val dark_onSurface = Color(0xFFe9e0e3)
val dark_surfaceVariant = Color(0xFF4f434a)
val dark_onSurfaceVariant = Color(0xFFd2c2ca)
val dark_outline = Color(0xFF9a8d94)
val dark_inverseOnSurface = Color(0xFF1f1a1d)
val dark_inverseSurface = Color(0xFFe9e0e3)
val dark_inversePrimary = Color(0xFF8e437e)
val dark_shadow = Color(0xFF000000)

val seed = Color(0xFF8a427a)
val error = Color(0xFFba1b1b)